/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creatingRGBColourPreview;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Malik
 */
public class RGBColourPreview extends JPanel {

    private int red = 0;
    private int green = 0;
    private int blue = 0;

    /**
     * Creates new form RGBColourPreview
     */
    public RGBColourPreview() {
        initComponents();
    }

    public int[] getRGB() {
        int[] RGB = new int[3];
        RGB[0] = red;
        RGB[1] = green;
        RGB[2] = blue;
        return RGB;
    }

    public void setRGB(int value, int value2, int value3) {
        red = value;
        green = value2;
        blue = value3;
        ColourPreview.setBackground(new Color(red, green, blue));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColourPreview = new javax.swing.JLabel();

        ColourPreview.setBackground(new java.awt.Color(126, 126, 126));
        ColourPreview.setText("           ");
        ColourPreview.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ColourPreview.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColourPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColourPreview)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColourPreview;
    // End of variables declaration//GEN-END:variables
}
